import type { CalendarEvent } from "../types";

export const TOTAL_MINUTES_IN_DAY = 24 * 60; // 1440 minutos
export const SLOT_HEIGHT_PX = 50; // 50px por slot
export const TOTAL_SLOTS = 96; // 24 horas * 4 slots por hora
export const HEADER_HEIGHT_PX = 28; // h-7 = 1.75rem = 28px del header
export const CONTAINER_HEIGHT_PX =
  TOTAL_SLOTS * SLOT_HEIGHT_PX + HEADER_HEIGHT_PX; // 4800px + 28px

export const initialEvents: CalendarEvent[] = [
  {
    id: "11",
    title: "Prueba 1",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-stone-50",
    hoverColor: "hover:bg-stone-100",
    textColor: "text-stone-700",
    descriptionColor: "text-stone-500 group-hover:text-stone-700",
  },
  {
    id: "12",
    title: "Prueba 2",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-blue-50",
    hoverColor: "hover:bg-slate-100",
    textColor: "text-slate-700",
    descriptionColor: "text-slate-500 group-hover:text-slate-700",
  },
  {
    id: "13",
    title: "Prueba 3",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "14",
    title: "Prueba 4",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "15",
    title: "Prueba 1",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "16",
    title: "Prueba 2",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "17",
    title: "Prueba 3",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "18",
    title: "Prueba 4",
    startTime: "04:00",
    endTime: "05:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },

  // Solapamiento parcial
  {
    id: "1",
    title: "Morning Jog",
    startTime: "06:00",
    endTime: "07:00",
    bgColor: "bg-green-50",
    hoverColor: "hover:bg-green-100",
    textColor: "text-green-700",
    descriptionColor: "text-green-500 group-hover:text-green-700",
  },
  {
    id: "2",
    title: "Breakfast",
    startTime: "06:30",
    endTime: "07:30",
    bgColor: "bg-yellow-50",
    hoverColor: "hover:bg-yellow-100",
    textColor: "text-yellow-700",
    descriptionColor: "text-yellow-600 group-hover:text-yellow-700",
  },
  {
    id: "3",
    title: "Team Standup",
    startTime: "07:00",
    endTime: "08:00",
    bgColor: "bg-blue-50",
    hoverColor: "hover:bg-blue-100",
    textColor: "text-blue-700",
    descriptionColor: "text-blue-500 group-hover:text-blue-700",
  },

  // Colisión total inicio
  {
    id: "4",
    title: "Client Call A",
    startTime: "09:00",
    endTime: "10:00",
    bgColor: "bg-pink-50",
    hoverColor: "hover:bg-pink-100",
    textColor: "text-pink-700",
    descriptionColor: "text-pink-500 group-hover:text-pink-700",
  },
  {
    id: "5",
    title: "Client Call B",
    startTime: "09:00",
    endTime: "09:45",
    bgColor: "bg-red-50",
    hoverColor: "hover:bg-red-100",
    textColor: "text-red-700",
    descriptionColor: "text-red-500 group-hover:text-red-700",
  },
  {
    id: "6",
    title: "Client Call C",
    startTime: "09:00",
    endTime: "10:30",
    bgColor: "bg-purple-50",
    hoverColor: "hover:bg-purple-100",
    textColor: "text-purple-700",
    descriptionColor: "text-purple-500 group-hover:text-purple-700",
  },

  // Eventos aislados
  {
    id: "7",
    title: "Lunch Break",
    startTime: "12:00",
    endTime: "13:00",
    bgColor: "bg-orange-50",
    hoverColor: "hover:bg-orange-100",
    textColor: "text-orange-700",
    descriptionColor: "text-orange-500 group-hover:text-orange-700",
  },

  // Solapamiento parcial largo
  {
    id: "8",
    title: "Project Work",
    startTime: "13:30",
    endTime: "15:00",
    bgColor: "bg-teal-50",
    hoverColor: "hover:bg-teal-100",
    textColor: "text-teal-700",
    descriptionColor: "text-teal-500 group-hover:text-teal-700",
  },
  {
    id: "9",
    title: "Code Review",
    startTime: "14:00",
    endTime: "15:30",
    bgColor: "bg-cyan-50",
    hoverColor: "hover:bg-cyan-100",
    textColor: "text-cyan-700",
    descriptionColor: "text-cyan-500 group-hover:text-cyan-700",
  },
  {
    id: "10",
    title: "Meeting with HR",
    startTime: "15:00",
    endTime: "16:00",
    bgColor: "bg-lime-50",
    hoverColor: "hover:bg-lime-100",
    textColor: "text-lime-700",
    descriptionColor: "text-lime-500 group-hover:text-lime-700",
  },
];
